AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.vendor/**/*'
    - '.git/**/*'
    - '_open_api/**/*'

# Temporarily disabled until we can refactor
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Always enabled
Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockComments:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Next:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
