navigation_weight:
  Messaging: 1
  SMS: 1
  Voice: 2
  Verify: 3
  Number Insight: 4
  Messages: 5
  Dispatch: 6
  Numbers: 98
  Account: 99
  Vonage Business Cloud: 7

  Number Programmability: 1
  Getting Started: 2
  Account API: 3
  Extension API: 4
  User API: 5

  Onboarding: 0
  Overview: 1
  Developer Preview: 2
  Tasks: 3
  Quickstarts: 3
  Guides: 4
  Code Snippets: 5

  Tutorials: 6
  Troubleshooting: 7
  API Reference: 7
  Conversation: 8

  Voice API: 1
  SIP: 2

  Client SDK: 30
  NCCO Reference: 40
  SDK Documentation: 40
  API Reference: 50

  Overview: 1
  Concepts: 2
  In-App Messaging: 3
  In-App Voice: 4
  In-App Video: 5

  Messages API: 1
  Dispatch API: 2

  Secret Management: 30

navigation_overrides:
  concepts:
    navigation_weight: 0
    svg: 'mind-map'
    svgColor: 'red'
  messaging:
    svg: 'message'
    svgColor: 'purple'
  voice:
    svg: 'phone'
    svgColor: 'green'
    voice-api:
      guides:
        lex-connector:
          label: 'Developer Preview'
        websockets:
          label: 'Beta'
  verify:
    svg: 'lock'
    svgColor: 'indigo'
  number-insight:
    svg: 'file-search'
    svgColor: 'orange'
  account:
    svg: 'user'
    svgColor: 'blue'
  redact:
    label: 'Developer Preview'
    svg: 'lock'
    svgColor: 'red'
  client-sdk:
    svg: 'queue'
    svgColor: 'teal'
    label: 'Developer Preview'
    sdk-documentation:
      link: false
      prevent_navigation_item_class: true
  numbers:
    svg: 'phone-number'
    svgColor: 'red'
  audit:
    svg: 'file-search'
    svgColor: 'green'
    label: 'Beta'
  messages:
    svg: 'chat'
    svgColor: 'purple'
    label: 'Beta'
  dispatch:
    svg: 'flow'
    svgColor: 'purple'
    label: 'Beta'
  conversation:
    svg: 'message'
    svgColor: 'teal'
    label: 'Developer Preview'
  vonage-business-cloud:
    svg: 'telephone'
    svgColor: 'green'
    label: 'Developer Preview'
  contribute:
    administration:
      navigation_weight: 9999
