# Default landing config page

# Column Types: 
# header, building_block, call_to_action, tutorial, sdk, join_slack, github_org, github_repo, structured_text, linked_image, text, html,
# action_button

# building_block: name (i.e. messaging/sms), language (i.e. ruby), pretext, posttext
# call_to_action: header, icon, subheader
# tutorial: name
# sdk: name
# text: text
# structured_text: header, icon, text (content, type (large or small))
# linked_image: image, url, alt_text
# action_button: text, url
# html: html

# columns width: if "width" is not provided then default to 100%

title: "Welcome to Nexmo, Residents of Jupiter"
meta_title: "A longer title goes here."

page:
  - row:
    - column: 
      - type: header
        header:
          title: "Thanks for joining us!"
          subtitle: "So glad you made it to OneHack Jupiter!"
          icon: "onehack-icon"
      - type: linked_image
        linked_image:
          image:
          url:
          alt_text:  
  - row:
    - width: 2
      column:
      - type: building_block
        building_block:
          name: messaging/sms
          language: ruby
          pre_text:
          post_text:
    - width: 2
      column:
      - type: building_block
        building_block:
          name: messaging/send-an-sms
          language: python
          pre_text:
          post_text:
  - row:
    - width: 1 
      column:
      - type: call_to_action
        call_to_action:
          header: "Sign Up"
          icon: "sign-up"
          subheader: "Try it for free"
    - width: 1
      column: 
      - type: join_slack
    - width: 1
      column: 
      - type: github_org
        github_org:
          name: nexmo
    - width: 1
      column:
      - type: github_repo
        github_repo:
          org: nexmo
          name: nexmo-php
  - row: 
    - width: 1
      column:
      - type: tutorial
        tutorial:
          name: call-tracking
    - width: 1
      column:
      - type: tutorial
        tutorial:
          name: receive-sms-with-ruby
    - width: 2 
      column:
      - type: sdk
        sdk:
          name: ruby
  - row: 
    - width: 1
      column: 
      - type: text
        text:
          content: Your awesome content
    - width: 1
      column:
      - type: text
        text:
          content: More awesome content
    - width: 1
      column:
      - type: html
        html:
          content: <a href="/find/me/here">Amazing things</a>
    - width: 1
      column:
      - type: structured_text
        structured_text:
          header: "This is the header text"
          icon: "icon-lightbulb"
          text:
            - content: "This is bigger text."
              type: large
            - content: "This is small text block."
              type: small
            - content: "This is another small text block underneath it."
              type: small