title: "Nexmo Voice SDK Onboarding"

page:
  - row:
    - column:
      - type: header
        header:
          title:
            text: "Nexmo In-App Voice"
            align: center
          subtitle:
            text: "Nexmo In-App Voice includes all you need to build a feature-rich voice experience.<br />If you can't find what you're looking for, you can [explore the Nexmo Client SDK](/client-sdk/overview)."
            align: center
          icon:
            name: "icon-phone"
            color: "green"

  - row:
    - column:
      - type: header
        header:
          title:
            text: "Quickstart"
          icon: 
            name: "icon-check"
            color: "blue-dark"
          subtitle:
            text: "Use one of our tutorials to create an app from scratch to fit your use case."

  - row:
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-javascript-color"></use></svg>
              JavaScript
            </h2>
      - type: html
        html:
          content: |
            <a class="Vlt-card" href="https://www.nexmo.com/blog/2019/03/15/full-stack-nexmo-with-express-react-dr/">
              <h4 class="Vlt-margin--top2">Build a Full Stack Nexmo App with Express and React</h4>
              <p>The Nexmo Node and JS Client SDKs along with Express and React can create a full-stack app as a basis for most things you may want from Nexmo in the browser</p>
            </a>
      - type: tutorial
        tutorial:
          name: client-sdk-js-outbound-call
      - type: tutorial
        tutorial:
          name: client-sdk-js-inbound-call
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-android-color"></use></svg>
              Android
            </h2>
      - type: tutorial
        tutorial:
          name: client-sdk-android-in-app-calling
      - type: tutorial
        tutorial:
          name: client-sdk-android-outbound-call
      - type: tutorial
        tutorial:
          name: client-sdk-android-inbound-call

    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-apple-color"></use></svg>
              iOS
            </h2>
      - type: tutorial
        tutorial:
          name: client-sdk-ios-in-app-calling
      - type: tutorial
        tutorial:
          name: client-sdk-ios-outbound-call
      - type: tutorial
        tutorial:
          name: client-sdk-ios-inbound-call

  - row:
    - column:
        - type: line_divider

  - row:
    - column:
      - type: header
        header:
          title:
            text: "Integrate"
          icon: 
            name: "icon-fork"
            color: "blue-dark"
          subtitle:
            text: "Use one of our guides to integrate Nexmo into your existing app."

  - row:
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-javascript-color"></use></svg>
              JavaScript
            </h2>
      - type: tutorial
        tutorial:
          name: client-sdk-js-add-sdk-to-your-app
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-android-color"></use></svg>
              Android
            </h2>
      - type: tutorial
        tutorial:
          name: client-sdk-android-add-sdk-to-your-app
      - type: tutorial
        tutorial:
          name: client-sdk-android-set-up-push-notifications
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-apple-color"></use></svg>
              iOS
            </h2>
      - type: tutorial
        tutorial:
          name: client-sdk-ios-add-sdk-to-your-app
      - type: tutorial
        tutorial:
          name: client-sdk-ios-set-up-push-notifications

  - row:
    - column:
      - type: line_divider

  - row:
    - column:
      - type: html
        html:
          content: '&nbsp;'
    - column:
      - type: action_button
        action_button:
          text: "Sign-up For Free"
          url: "https://dashboard.nexmo.com/sign-up?utm_source=nexmo-developer&utm_medium=voice-onboarding&utm_campaign=landing"
          center_button: true
          type: secondary
          large: true
    - column:
      - type: action_button
        action_button:
          text: "View Nexmo docs"
          url: "/"
          center_button: true
          type: secondary
          large: true
    - column:
      - type: html
        html:
          content: '&nbsp;'

  - row:
    - column:
        - type: line_divider
  - row:
    - column:
      - type: join_slack
  - row:
    - column:
        - type: line_divider
